name: CI/CD to Huawei SWR and CCE

on:
  push:
    branches:
      - master  # Trigger CI/CD when code is pushed to the 'master' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      #- name: Build Docker image
      #  run: docker buildx build -t hello ./src/*/Dockerfile

      - name: Log in to Huawei Cloud SWR
        uses: huaweicloud/swr-login@v2.1.0
        with:
          access-key-id: ${{ secrets.ACCESSKEY }}
          access-key-secret: ${{ secrets.SECRETACCESSKEY }}
          region: af-south-1

      - name: Build and push Docker image
        run: |
          docker build -t swr.af-south-1.myhuaweicloud.com/ralf/adservice:${{ github.sha }} ./src/adservice/
          docker push swr.af-south-1.myhuaweicloud.com/ralf/adservice:${{ github.sha }}

      - name: Build and push Docker image
        run: |
          docker build -t swr.af-south-1.myhuaweicloud.com/ralf/cartservice:${{ github.sha }} ./src/cartservice/src/
          docker push swr.af-south-1.myhuaweicloud.com/ralf/cartservice:${{ github.sha }}

      - name: Build and push Docker image
        run: |
          docker build -t swr.af-south-1.myhuaweicloud.com/ralf/checkoutservice:${{ github.sha }} ./src/checkoutservice/
          docker push swr.af-south-1.myhuaweicloud.com/ralf/checkoutservice:${{ github.sha }}


       - name: Build and push Docker image
        run: |
          docker build -t swr.af-south-1.myhuaweicloud.com/ralf/currencyservice:${{ github.sha }} ./src/currencyservice/
          docker push swr.af-south-1.myhuaweicloud.com/ralf/currencyservice:${{ github.sha }}

      - name: Build and push Docker image
        run: |
          docker build -t swr.af-south-1.myhuaweicloud.com/ralf/emailservice:${{ github.sha }} ./src/emailservice/
          docker push swr.af-south-1.myhuaweicloud.com/ralf/emailservice:${{ github.sha }}

      - name: Build and push Docker image
        run: |
          docker build -t swr.af-south-1.myhuaweicloud.com/ralf/frontend:${{ github.sha }} ./src/frontend
          docker push swr.af-south-1.myhuaweicloud.com/ralf/frontend:${{ github.sha }}

      - name: Build and push Docker image
        run: |
          docker build -t swr.af-south-1.myhuaweicloud.com/ralf/loadgenerator:${{ github.sha }} ./src/loadgenerator/
          docker push swr.af-south-1.myhuaweicloud.com/ralf/loadgenerator:${{ github.sha }}

      - name: Build and push Docker image
        run: |
          docker build -t swr.af-south-1.myhuaweicloud.com/ralf/paymentservice:${{ github.sha }} ./src/paymentservice/
          docker push swr.af-south-1.myhuaweicloud.com/ralf/paymentservice:${{ github.sha }}
          

      - name: Build and push Docker image
        run: |
          docker build -t swr.af-south-1.myhuaweicloud.com/ralf/productcatalogservice:${{ github.sha }} ./src/productcatalogservice/
          docker push swr.af-south-1.myhuaweicloud.com/ralf/productcatalogservice:${{ github.sha }}

      - name: Build and push Docker image
        run: |
          docker build -t swr.af-south-1.myhuaweicloud.com/ralf/recommendationservice:${{ github.sha }} ./src/recommendationservice/
          docker push swr.af-south-1.myhuaweicloud.com/ralf/recommendationservice:${{ github.sha }}

      - name: Build and push Docker image
        run: |
          docker build -t swr.af-south-1.myhuaweicloud.com/ralf/shippingservice:${{ github.sha }} ./src/shippingservice/
          docker push swr.af-south-1.myhuaweicloud.com/ralf/shippingservice:${{ github.sha }}


  

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure kubectl for Huawei Cloud CCE
        run: |
          sudo mkdir -p $HOME/.kube
          sudo chown -R runner:runner $HOME/.kube
          export KUBECONFIG=$HOME/.kube/config
          echo "${{ secrets.KUBE_CONFIG_DATA }}" > $KUBECONFIG
      - name: Update deployment
        run: |
          sed -i "s@swr.af-south-1.myhuaweicloud.com/ralf/hello-world-nodejs:[a-z0-9]*@swr.af-south-1.myhuaweicloud.com/ralf/hello-world-nodejs:${{ github.sha }}@g" deployment.yaml    
          sed -i "s@swr.af-south-1.myhuaweicloud.com/ralf/hello-world-nodejs:[a-z0-9]*@swr.af-south-1.myhuaweicloud.com/ralf/hello-world-nodejs:${{ github.sha }}@g" deployment.yaml    
          sed -i "s@swr.af-south-1.myhuaweicloud.com/ralf/hello-world-nodejs:[a-z0-9]*@swr.af-south-1.myhuaweicloud.com/ralf/hello-world-nodejs:${{ github.sha }}@g" deployment.yaml    
          sed -i "s@swr.af-south-1.myhuaweicloud.com/ralf/hello-world-nodejs:[a-z0-9]*@swr.af-south-1.myhuaweicloud.com/ralf/hello-world-nodejs:${{ github.sha }}@g" deployment.yaml    
          sed -i "s@swr.af-south-1.myhuaweicloud.com/ralf/hello-world-nodejs:[a-z0-9]*@swr.af-south-1.myhuaweicloud.com/ralf/hello-world-nodejs:${{ github.sha }}@g" deployment.yaml    
          sed -i "s@swr.af-south-1.myhuaweicloud.com/ralf/hello-world-nodejs:[a-z0-9]*@swr.af-south-1.myhuaweicloud.com/ralf/hello-world-nodejs:${{ github.sha }}@g" deployment.yaml    
          sed -i "s@swr.af-south-1.myhuaweicloud.com/ralf/hello-world-nodejs:[a-z0-9]*@swr.af-south-1.myhuaweicloud.com/ralf/hello-world-nodejs:${{ github.sha }}@g" deployment.yaml    
          sed -i "s@swr.af-south-1.myhuaweicloud.com/ralf/hello-world-nodejs:[a-z0-9]*@swr.af-south-1.myhuaweicloud.com/ralf/hello-world-nodejs:${{ github.sha }}@g" deployment.yaml    
          sed -i "s@swr.af-south-1.myhuaweicloud.com/ralf/hello-world-nodejs:[a-z0-9]*@swr.af-south-1.myhuaweicloud.com/ralf/hello-world-nodejs:${{ github.sha }}@g" deployment.yaml    
          sed -i "s@swr.af-south-1.myhuaweicloud.com/ralf/hello-world-nodejs:[a-z0-9]*@swr.af-south-1.myhuaweicloud.com/ralf/hello-world-nodejs:${{ github.sha }}@g" deployment.yaml    
          sed -i "s@swr.af-south-1.myhuaweicloud.com/ralf/hello-world-nodejs:[a-z0-9]*@swr.af-south-1.myhuaweicloud.com/ralf/hello-world-nodejs:${{ github.sha }}@g" deployment.yaml    


      - name: Debugging
        run: |
          kubectl version
          kubectl cluster-info
          kubectl get nodes

      - name: Deploy to Huawei CCE
        run: |
          kubectl apply -f .release/
